"""
Open-data endpoints: serve the RDF export files (dumps/rdf) for the /data page.

The dumps are generated by `make export-rdf` (build/export_rdf.py); if they are
missing the manifest is simply empty and the frontend falls back to the
"Zenodo in preparation" note.
"""
import logging
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/data", tags=["Data"])

RDF_DIR = Path(__file__).resolve().parents[3] / "dumps" / "rdf"
ALLOWED_FILES = {
    "parliamentrag_kg.ttl": "text/turtle",
    "parliamentrag_votes.nt": "application/n-triples",
}


@router.get("/rdf")
async def rdf_manifest():
    """List the RDF dump files available on this server."""
    files = []
    for name in ALLOWED_FILES:
        path = RDF_DIR / name
        if path.is_file():
            files.append({"filename": name, "bytes": path.stat().st_size})
    return {"files": files}


@router.get("/rdf/{filename}")
async def rdf_file(filename: str):
    """Stream one RDF dump file as a download."""
    media_type = ALLOWED_FILES.get(filename)
    if media_type is None:
        raise HTTPException(status_code=404, detail="Unknown file")
    path = RDF_DIR / filename
    if not path.is_file():
        raise HTTPException(
            status_code=404,
            detail="Dump not generated on this server yet (make export-rdf)",
        )
    return FileResponse(path, media_type=media_type, filename=filename)
