"""
Open-data endpoints: serve the RDF export files (dumps/rdf) for the /data page.

The dumps are generated by `make export-rdf` (build/export_rdf.py); if they are
missing the manifest is simply empty and the frontend falls back to the
"Zenodo in preparation" note.
"""
import json
import logging
import re
import time
from datetime import date
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/data", tags=["Data"])

RDF_DIR = Path(__file__).resolve().parents[3] / "dumps" / "rdf"
ALLOWED_FILES = {
    "parliamentrag_kg.ttl": "text/turtle",
    "parliamentrag_votes.nt": "application/n-triples",
}

STATS_LABELS = {
    "people": "Person",
    "speeches": "Speech",
    "sessions": "Session",
    "acts": "ParliamentaryAct",
    "votes": "Vote",
    "individual_votes": "IndividualVote",
    "eurovoc_concepts": "EurovocConcept",
    "chunks": "Chunk",
}
_STATS_TTL_S = 3600
_stats_cache: dict = {"at": 0.0, "data": None}


@router.get("/stats")
async def kg_stats():
    """Live KG counts (label counts are O(1) via the Neo4j count store).

    `triples` comes from the last RDF export (dumps/rdf/export_meta.json,
    written by build/export_rdf.py) and is null if no export has run here.
    """
    now = time.time()
    if _stats_cache["data"] is not None and now - _stats_cache["at"] < _STATS_TTL_S:
        return _stats_cache["data"]

    from ..services.deps import get_services

    client = get_services()["neo4j"]
    data: dict = {}
    for key, label in STATS_LABELS.items():
        result = client.query(f"MATCH (n:`{label}`) RETURN count(n) AS c")
        data[key] = result[0]["c"] if result else None

    # Last `make update-data` run; falls back to newest Session date for
    # DBs stamped before SchemaMeta.updated_at existed
    result = client.query(
        "OPTIONAL MATCH (m:SchemaMeta {id: 'singleton'}) "
        "WITH date(m.updated_at) AS stamped "
        "OPTIONAL MATCH (s:Session) "
        "WITH stamped, max(s.date) AS newest "
        "RETURN coalesce(stamped, newest) AS last_date"
    )
    last = result[0].get("last_date") if result else None
    data["last_update"] = str(last.to_native() if hasattr(last, "to_native") else last) if last else None

    data["triples"] = None
    meta_path = RDF_DIR / "export_meta.json"
    if meta_path.is_file():
        try:
            data["triples"] = json.loads(meta_path.read_text()).get("triples")
        except (json.JSONDecodeError, OSError) as e:
            logger.warning("Unreadable export_meta.json: %s", e)

    _stats_cache.update(at=now, data=data)
    return data


@router.get("/graph-sample")
async def graph_sample():
    """A random deputy with real neighbours, for the /data hero figure.

    Nulls are possible (deputy without acts or votes): the frontend keeps its
    static fallback for those fields.
    """
    from ..services.deps import get_services

    client = get_services()["neo4j"]
    person = client.query_single(
        "MATCH (p:Deputy)-[m:MEMBER_OF_GROUP]->(g:ParliamentaryGroup) "
        "WHERE m.end_date IS NULL "
        "WITH p, m, g, rand() AS r ORDER BY r LIMIT 1 "
        "RETURN p.id AS id, p.first_name AS first_name, p.last_name AS last_name, "
        "p.term_of_office AS mandate, toString(m.start_date) AS membership_start, "
        "coalesce(g.acronym, g.name) AS group_label"
    )
    if not person:
        raise HTTPException(status_code=404, detail="No deputies in the graph")
    pid = person["id"]

    speech = client.query_single(
        "MATCH (s:Speech)-[:SPOKEN_BY]->(:Person {id: $id}) "
        "WITH s, rand() AS r ORDER BY r LIMIT 1 RETURN s.id AS id",
        {"id": pid},
    )
    act = client.query_single(
        "MATCH (:Person {id: $id})-[:PRIMARY_SIGNATORY]->(a:ParliamentaryAct) "
        "WHERE a.uri STARTS WITH 'http' "
        "OPTIONAL MATCH (a)-[:HAS_SUBJECT]->(e:EurovocConcept) "
        "WITH a, e, rand() AS r ORDER BY e IS NULL, r LIMIT 1 "
        "RETURN a.uri AS uri, e.label_it AS topic",
        {"id": pid},
    )
    vote = client.query_single(
        "MATCH (:Person {id: $id})-[:VOTED]->(:IndividualVote)-[:ON_VOTE]->(v:Vote) "
        "WITH v, rand() AS r ORDER BY r LIMIT 1 RETURN v.id AS id",
        {"id": pid},
    )
    group_slug = re.sub(r"[^a-z0-9]+", "-", (person["group_label"] or "").lower()).strip("-")[:24]
    mandate = person["mandate"] or ""
    return {
        "person": {
            "id": pid.rsplit("/", 1)[-1],
            "first_name": person["first_name"],
            "last_name": person["last_name"],
        },
        "group": person["group_label"],
        "group_slug": group_slug,
        "membership_start": person["membership_start"],
        "mandate": mandate.rsplit("/", 1)[-1] if mandate else None,
        "speech": speech["id"] if speech else None,
        "act": act["uri"].rsplit("/", 1)[-1] if act else None,
        "topic": act["topic"] if act else None,
        "vote": vote["id"] if vote else None,
    }


@router.get("/rdf")
async def rdf_manifest():
    """List the RDF dump files available on this server."""
    files = []
    for name in ALLOWED_FILES:
        path = RDF_DIR / name
        if path.is_file():
            stat = path.stat()
            files.append({
                "filename": name,
                "bytes": stat.st_size,
                "modified": date.fromtimestamp(stat.st_mtime).isoformat(),
            })
    return {"files": files}


@router.get("/rdf/{filename}")
async def rdf_file(filename: str):
    """Stream one RDF dump file as a download."""
    media_type = ALLOWED_FILES.get(filename)
    if media_type is None:
        raise HTTPException(status_code=404, detail="Unknown file")
    path = RDF_DIR / filename
    if not path.is_file():
        raise HTTPException(
            status_code=404,
            detail="Dump not generated on this server yet (make export-rdf)",
        )
    return FileResponse(path, media_type=media_type, filename=filename)
